### ISSUE TITLE
Пропущены краевые случаи при разделении строки на слова.

### ISSUE THREAD

**Issue by xWillQ** [PetrSed/se-test#1]
Если в строке будет несколько пробелов подряд, то split(' ') разделит на пустые строки.
https://github.com/PetrSed/GoodLine-Kafedra-se-test/blob/6899f6507c867c96fbbbe6707b3157b035a49f79/6.kt#L7
![image](https://user-images.githubusercontent.com/38136135/75606046-7f86b280-5b1b-11ea-8ba0-de8a8e07fa60.png)

**Comment by PetrSed** [comment]
Спасибо, поправлю)
