### ISSUE TITLE
Исправить codestyle с помощью горячих клавиш IDEA

### ISSUE THREAD

**Issue by ABashkirova** [PetrSed/se-test#2]
[Соглашения по kotlin codestyle](https://kotlinlang.org/docs/reference/coding-conventions.html)
В задачах 4, 5 и 6

**Comment by PetrSed** [comment]
Спасибо, поправлю)

**Comment by kozlyakov-m** [comment]
Одними горячими клавишами не обойтись, во всех трех задачах неправильные названия переменных

**Comment by PetrSed** [comment]
Знаю, поправлю
