### ISSUE TITLE
изменить var на val

### ISSUE THREAD

**Issue by kozlyakov-m** [PetrSed/se-test#3]
переменные arg_dict и sorted_args не изменяются в ходе выполнения, рекомендуется объявлять их как val
а ещё их надо переименовать в argDict и sortedArgs)

https://github.com/PetrSed/GoodLine-Kafedra-se-test/blob/6899f6507c867c96fbbbe6707b3157b035a49f79/6.kt#L9

**Comment by PetrSed** [comment]
Спасибо, поправлю)
